apiVersion: v1
kind: PersistentVolume
metadata:
  name: $volumeId
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/disk"
    fsType: "ext4"
    options:
      volumeId: "$volumeId"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $namespace
 name: $volumeId
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: $namespace
  name:	$podName
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
       app: hyperledger
       role: peer
       peer-id: $peerID
       org: $namespace
    spec:
      affinity:
       podAntiAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
         - weight: 100
           podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "role"
                  operator: In
                  values:
                  - peer
                - key: "org"
                  operator: In
                  values:
                  - $namespace
              topologyKey: "kubernetes.io/hostname"
      containers:
#      - name: couchdb
#        image: hyperledger/fabric-couchdb:x86_64-0.10
#        ports:
#         - containerPort: 5984
#

      - name: $podName 
        image: hyperledger/fabric-peer:x86_64-1.1.0-preview
        env:
#        - name: CORE_LEDGER_STATE_STATEDATABASE
#          value: "CouchDB"
#        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
#          value: "localhost:5984"
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: CORE_LOGGING_LEVEL
          value: "DEBUG"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false" 
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/etc/hyperledger/fabric/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/etc/hyperledger/fabric/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/etc/hyperledger/fabric/tls/ca.crt"
        - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
          value: $corePeerID
        - name: CORE_PEER_ID
          value: $corePeerID
        - name: CORE_PEER_ADDRESS
          value: $peerAddress
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: $peerGossip
        - name: CORE_PEER_LOCALMSPID
          value: $localMSPID
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/fabric/msp
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: aliyun_logs_fluentd
          value: "stdout"

        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
         - containerPort: 7051
         - containerPort: 7052
         - containerPort: 7053
        command: ["peer"]
        args: ["node","start"]
        volumeMounts:
         #- mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
         #  name: certificate
         #  subPath: channel-artifacts
         - mountPath: /etc/hyperledger/fabric/msp
           name: certificate
           #subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
           subPath: $mspPath
         - mountPath: /etc/hyperledger/fabric/tls
           name: certificate
           #subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/
           subPath: $tlsPath
         - mountPath: /host/var/run/
           name: run
         - mountPath: /var/hyperledger/production
           name: data
      volumes:
       - name: certificate
         persistentVolumeClaim:
             claimName: $pvName
       - name: data
         persistentVolumeClaim:
             claimName: $volumeId
       - name: run
         hostPath:
           path: /run
---
apiVersion: v1
kind: Service
metadata:
   namespace: $namespace
   name: $peerID
spec:
 selector:
   app: hyperledger
   role: peer
   peer-id: $peerID
   org: $namespace
 clusterIP: None
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: 7051

   - name: chaincode-listen
     protocol: TCP
     port: 7052

   - name: event-listen
     protocol: TCP
     port: 7053
---
apiVersion: v1
kind: Service
metadata:
   namespace: $namespace
   name: $peerID-ex
spec:
 selector:
   app: hyperledger
   role: peer
   peer-id: $peerID
   org: $namespace
 type: NodePort
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
     nodePort: $nodePort1

   - name: chaincode-listen
     protocol: TCP
     port: 7052
     targetPort: 7052
     nodePort: $nodePort2

   - name: event-listen
     protocol: TCP
     port: 7053
     targetPort: 7053
     nodePort: $nodePort3
---
